
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class playerAttributes : Luban.BeanBase
{
    public playerAttributes(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["role_id"].IsNumber) { throw new SerializationException(); }  RoleId = _buf["role_id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["max_level"].IsNumber) { throw new SerializationException(); }  MaxLevel = _buf["max_level"]; }
        { if(!_buf["attack"].IsNumber) { throw new SerializationException(); }  Attack = _buf["attack"]; }
        { if(!_buf["defence"].IsNumber) { throw new SerializationException(); }  Defence = _buf["defence"]; }
        { if(!_buf["health"].IsNumber) { throw new SerializationException(); }  Health = _buf["health"]; }
        { if(!_buf["coldTime"].IsNumber) { throw new SerializationException(); }  ColdTime = _buf["coldTime"]; }
        { if(!_buf["nextLevel"].IsNumber) { throw new SerializationException(); }  NextLevel = _buf["nextLevel"]; }
        { if(!_buf["walkSpeed"].IsNumber) { throw new SerializationException(); }  WalkSpeed = _buf["walkSpeed"]; }
        { if(!_buf["runSpeed"].IsNumber) { throw new SerializationException(); }  RunSpeed = _buf["runSpeed"]; }
    }

    public static playerAttributes DeserializeplayerAttributes(JSONNode _buf)
    {
        return new playerAttributes(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 角色id
    /// </summary>
    public readonly int RoleId;
    /// <summary>
    /// 角色名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 最高等级
    /// </summary>
    public readonly int MaxLevel;
    /// <summary>
    /// 基础攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 基础防御力
    /// </summary>
    public readonly int Defence;
    /// <summary>
    /// 基础生命值
    /// </summary>
    public readonly int Health;
    /// <summary>
    /// 技能冷却时间
    /// </summary>
    public readonly float ColdTime;
    /// <summary>
    /// 下一等级所需经验
    /// </summary>
    public readonly int NextLevel;
    /// <summary>
    /// 行走速度
    /// </summary>
    public readonly float WalkSpeed;
    /// <summary>
    /// 奔跑速度
    /// </summary>
    public readonly float RunSpeed;
   
    public const int __ID__ = -817448168;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "roleId:" + RoleId + ","
        + "name:" + Name + ","
        + "level:" + Level + ","
        + "maxLevel:" + MaxLevel + ","
        + "attack:" + Attack + ","
        + "defence:" + Defence + ","
        + "health:" + Health + ","
        + "coldTime:" + ColdTime + ","
        + "nextLevel:" + NextLevel + ","
        + "walkSpeed:" + WalkSpeed + ","
        + "runSpeed:" + RunSpeed + ","
        + "}";
    }
}
}

