
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbplayerAttributes TbplayerAttributes {get; }
    public TbplayerInfo TbplayerInfo {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbplayerAttributes = new TbplayerAttributes(loader("tbplayerattributes"));
        TbplayerInfo = new TbplayerInfo(loader("tbplayerinfo"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbplayerAttributes.ResolveRef(this);
        TbplayerInfo.ResolveRef(this);
    }
}

}
