
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbplayerInfo
{
    private readonly System.Collections.Generic.Dictionary<int, playerInfo> _dataMap;
    private readonly System.Collections.Generic.List<playerInfo> _dataList;
    
    public TbplayerInfo(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, playerInfo>(count);
        _dataList = new System.Collections.Generic.List<playerInfo>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            playerInfo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.playerInfo.DeserializeplayerInfo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, playerInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<playerInfo> DataList => _dataList;

    public playerInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public playerInfo Get(int key) => _dataMap[key];
    public playerInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

