
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbplayerAttributes
{
    private readonly System.Collections.Generic.Dictionary<int, playerAttributes> _dataMap;
    private readonly System.Collections.Generic.List<playerAttributes> _dataList;
    
    public TbplayerAttributes(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, playerAttributes>(count);
        _dataList = new System.Collections.Generic.List<playerAttributes>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            playerAttributes _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.playerAttributes.DeserializeplayerAttributes(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, playerAttributes> DataMap => _dataMap;
    public System.Collections.Generic.List<playerAttributes> DataList => _dataList;

    public playerAttributes GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public playerAttributes Get(int key) => _dataMap[key];
    public playerAttributes this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

